# Website settings
url: "https://rfishy1.github.io/"

# Internal nav
nav:
  main:
    writing: "/writing"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Richard Fisher-Monteith"
description: "The home page of Richard Fisher-Monteith."
thumbnail_path: "profile-photos/richard-fisher-monteith-medium.jpg"
website_repo_url: "https://github.com/rfishy1/rfishy.github.io"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/richardcarlfisher"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/rfishy1/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:richard.carl.fisher@gmail.com"
    label: "Email"
    value: "richard.carl.fisher@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: rfishy1/rfishy.github.io

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
