# Website settings
url: "https://rfishermonteith.github.io"

# Internal nav
nav:
  main:
    writing: "/writing"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Richard Fisher-Monteith"
description: "The home page of Richard Fisher-Monteith."
thumbnail_path: "profile-photos/richard-fisher-monteith-medium.jpg"
website_repo_url: "https://github.com/rfishermonteith/rfishermonteith.github.io"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/richardcarlfisher"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/rfishermonteith/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:richard.carl.fisher@gmail.com"
    label: "Email"
    value: "richard.carl.fisher@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'Europe/London'
repository: rfishermonteith/rfishermonteith.github.io

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

# Exclude code files
exclude:
  - "*.py"

piratepx_project_id: 57c14f04-8eff-4dcd-9c3e-a18e464b6962